modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/VazkiiMods/Neat"
license="MIT AND CC-BY-NC-SA-3.0"  # Code is MIT, assets are CC

[[mods]]
modId="neat"
displayName="Neat"
version="${version}"
authors="Vazkii, Uraneptus"
description="Minimalistic Functional Unit Plates for the modern Minecrafter"
logoFile="assets/neat/icon.png"

[[dependencies.neat]]
modId="neoforge"
type="required"
versionRange="[21.0.143,)"

[[dependencies.neat]]
modId="minecraft"
type="required"
versionRange="[1.21,)"

[[mixins]]
config="neat.mixins.json"
